[package]
name = "dfu-core"
version = "0.1.0"
edition = "2018"

[[bench]]
name = "file_contents_equal"
harness = false

[dependencies]
walkdir = "2.3.1"
itertools = "0.10.0"
thiserror = "1.0.24"

[dev-dependencies]
criterion = "0.3"
tempfile = "3.2.0"
